container:
  image: cirrusci/flutter:stable
  
analyze_task:
  pub_cache:
    folder: ~/.pub-cache
  analyze_script: flutter analyze

build_task:
  pub_cache:
    folder: ~/.pub-cache
  script:
    - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk

test_task:
  pub_cache:
    folder: ~/.pub-cache
  test_script: flutter test
