container:
  image: cirrusci/flutter:stable
pub_cache:
  folder: ~/.pub-cache
  
task:
  name: Run analyzer
  analyze_script: flutter analyze

task:
  name: Build app (Android)
  build_script:
    - flutter build apk --debug

task:
  name: Run tests
  test_script: flutter test
