name: bmi_calculator
description: A BMI calculator app developed with Flutter.
publish_to: 'none'
version: 3.0.0

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 1.0.0-dev.7
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  freezed_annotation: ^0.14.3
  intl: ^0.17.0
  shared_preferences: ^2.0.7

dev_dependencies:
  build_runner: ^2.1.2
  flutter_driver:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  test: any

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
